/* This file is generated by tools/stackvm_gen/IsaGen at 2023/1/30 17:07:38 +08:00.
 *
 * Copyright 2019-2021 Canaan Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <nncase/runtime/stackvm/op_reader.h>

using namespace nncase;
using namespace nncase::runtime;
using namespace nncase::runtime::stackvm;

result<void> tensor_op_visitor::visit(tensor_function_t tensor_funct, span_reader &reader) noexcept
{
     switch (tensor_funct)
     {
    case tensor_function_t::batch_normalization:
        return visit(op_reader<tensor_batch_normalization_op_t>()(reader));
    case tensor_function_t::batch_to_space:
        return visit(op_reader<tensor_batch_to_space_op_t>()(reader));
    case tensor_function_t::binary:
        return visit(op_reader<tensor_binary_op_t>()(reader));
    case tensor_function_t::bitcast:
        return visit(op_reader<tensor_bitcast_op_t>()(reader));
    case tensor_function_t::broadcast:
        return visit(op_reader<tensor_broadcast_op_t>()(reader));
    case tensor_function_t::cast:
        return visit(op_reader<tensor_cast_op_t>()(reader));
    case tensor_function_t::celu:
        return visit(op_reader<tensor_celu_op_t>()(reader));
    case tensor_function_t::clamp:
        return visit(op_reader<tensor_clamp_op_t>()(reader));
    case tensor_function_t::compare:
        return visit(op_reader<tensor_compare_op_t>()(reader));
    case tensor_function_t::concat:
        return visit(op_reader<tensor_concat_op_t>()(reader));
    case tensor_function_t::condition:
        return visit(op_reader<tensor_condition_op_t>()(reader));
    case tensor_function_t::constant_of_shape:
        return visit(op_reader<tensor_constant_of_shape_op_t>()(reader));
    case tensor_function_t::conv2d:
        return visit(op_reader<tensor_conv2d_op_t>()(reader));
    case tensor_function_t::conv2d_transpose:
        return visit(op_reader<tensor_conv2d_transpose_op_t>()(reader));
    case tensor_function_t::cum_sum:
        return visit(op_reader<tensor_cum_sum_op_t>()(reader));
    case tensor_function_t::dequantize:
        return visit(op_reader<tensor_dequantize_op_t>()(reader));
    case tensor_function_t::elu:
        return visit(op_reader<tensor_elu_op_t>()(reader));
    case tensor_function_t::expand:
        return visit(op_reader<tensor_expand_op_t>()(reader));
    case tensor_function_t::fake_dequantize:
        return visit(op_reader<tensor_fake_dequantize_op_t>()(reader));
    case tensor_function_t::fake_quantize:
        return visit(op_reader<tensor_fake_quantize_op_t>()(reader));
    case tensor_function_t::flatten:
        return visit(op_reader<tensor_flatten_op_t>()(reader));
    case tensor_function_t::gather:
        return visit(op_reader<tensor_gather_op_t>()(reader));
    case tensor_function_t::gather_nd:
        return visit(op_reader<tensor_gather_nd_op_t>()(reader));
    case tensor_function_t::get_item:
        return visit(op_reader<tensor_get_item_op_t>()(reader));
    case tensor_function_t::hard_sigmoid:
        return visit(op_reader<tensor_hard_sigmoid_op_t>()(reader));
    case tensor_function_t::hard_swish:
        return visit(op_reader<tensor_hard_swish_op_t>()(reader));
    case tensor_function_t::hardmax:
        return visit(op_reader<tensor_hardmax_op_t>()(reader));
    case tensor_function_t::instance_normalization:
        return visit(op_reader<tensor_instance_normalization_op_t>()(reader));
    case tensor_function_t::l2_normalization:
        return visit(op_reader<tensor_l2_normalization_op_t>()(reader));
    case tensor_function_t::leaky_relu:
        return visit(op_reader<tensor_leaky_relu_op_t>()(reader));
    case tensor_function_t::log_softmax:
        return visit(op_reader<tensor_log_softmax_op_t>()(reader));
    case tensor_function_t::lp_normalization:
        return visit(op_reader<tensor_lp_normalization_op_t>()(reader));
    case tensor_function_t::lrn:
        return visit(op_reader<tensor_lrn_op_t>()(reader));
    case tensor_function_t::lstm:
        return visit(op_reader<tensor_lstm_op_t>()(reader));
    case tensor_function_t::mat_mul:
        return visit(op_reader<tensor_mat_mul_op_t>()(reader));
    case tensor_function_t::normal:
        return visit(op_reader<tensor_normal_op_t>()(reader));
    case tensor_function_t::normal_like:
        return visit(op_reader<tensor_normal_like_op_t>()(reader));
    case tensor_function_t::one_hot:
        return visit(op_reader<tensor_one_hot_op_t>()(reader));
    case tensor_function_t::pad:
        return visit(op_reader<tensor_pad_op_t>()(reader));
    case tensor_function_t::prelu:
        return visit(op_reader<tensor_prelu_op_t>()(reader));
    case tensor_function_t::prod:
        return visit(op_reader<tensor_prod_op_t>()(reader));
    case tensor_function_t::quant_param_of:
        return visit(op_reader<tensor_quant_param_of_op_t>()(reader));
    case tensor_function_t::quantize:
        return visit(op_reader<tensor_quantize_op_t>()(reader));
    case tensor_function_t::range:
        return visit(op_reader<tensor_range_op_t>()(reader));
    case tensor_function_t::range_of:
        return visit(op_reader<tensor_range_of_op_t>()(reader));
    case tensor_function_t::reduce:
        return visit(op_reader<tensor_reduce_op_t>()(reader));
    case tensor_function_t::reduce_arg:
        return visit(op_reader<tensor_reduce_arg_op_t>()(reader));
    case tensor_function_t::reduce_window2d:
        return visit(op_reader<tensor_reduce_window2d_op_t>()(reader));
    case tensor_function_t::relu:
        return visit(op_reader<tensor_relu_op_t>()(reader));
    case tensor_function_t::relu6:
        return visit(op_reader<tensor_relu6_op_t>()(reader));
    case tensor_function_t::require:
        return visit(op_reader<tensor_require_op_t>()(reader));
    case tensor_function_t::reshape:
        return visit(op_reader<tensor_reshape_op_t>()(reader));
    case tensor_function_t::resize_image:
        return visit(op_reader<tensor_resize_image_op_t>()(reader));
    case tensor_function_t::reverse_sequence:
        return visit(op_reader<tensor_reverse_sequence_op_t>()(reader));
    case tensor_function_t::select:
        return visit(op_reader<tensor_select_op_t>()(reader));
    case tensor_function_t::selu:
        return visit(op_reader<tensor_selu_op_t>()(reader));
    case tensor_function_t::shape_of:
        return visit(op_reader<tensor_shape_of_op_t>()(reader));
    case tensor_function_t::sigmoid:
        return visit(op_reader<tensor_sigmoid_op_t>()(reader));
    case tensor_function_t::size_of:
        return visit(op_reader<tensor_size_of_op_t>()(reader));
    case tensor_function_t::slice:
        return visit(op_reader<tensor_slice_op_t>()(reader));
    case tensor_function_t::softmax:
        return visit(op_reader<tensor_softmax_op_t>()(reader));
    case tensor_function_t::softplus:
        return visit(op_reader<tensor_softplus_op_t>()(reader));
    case tensor_function_t::softsign:
        return visit(op_reader<tensor_softsign_op_t>()(reader));
    case tensor_function_t::space_to_batch:
        return visit(op_reader<tensor_space_to_batch_op_t>()(reader));
    case tensor_function_t::split:
        return visit(op_reader<tensor_split_op_t>()(reader));
    case tensor_function_t::squeeze:
        return visit(op_reader<tensor_squeeze_op_t>()(reader));
    case tensor_function_t::stack:
        return visit(op_reader<tensor_stack_op_t>()(reader));
    case tensor_function_t::tile:
        return visit(op_reader<tensor_tile_op_t>()(reader));
    case tensor_function_t::top_k:
        return visit(op_reader<tensor_top_k_op_t>()(reader));
    case tensor_function_t::transpose:
        return visit(op_reader<tensor_transpose_op_t>()(reader));
    case tensor_function_t::unary:
        return visit(op_reader<tensor_unary_op_t>()(reader));
    case tensor_function_t::uniform:
        return visit(op_reader<tensor_uniform_op_t>()(reader));
    case tensor_function_t::uniform_like:
        return visit(op_reader<tensor_uniform_like_op_t>()(reader));
    case tensor_function_t::unsqueeze:
        return visit(op_reader<tensor_unsqueeze_op_t>()(reader));
    case tensor_function_t::where:
        return visit(op_reader<tensor_where_op_t>()(reader));
    default:
        break;
    }

    return err(nncase_errc::stackvm_illegal_instruction);
}
