if (MSVC)
    add_definitions(/DX86_64_SIMD_ON)
    add_compile_options(/arch:AVX)
    add_compile_options(/arch:AVX2)
else()
    add_definitions(-DX86_64_SIMD_ON)
    add_compile_options(-mfma -msse -msse2 -msse3 -mssse3 -msse4 -msse4a -msse4.1 -msse4.2 -mavx -mavx2)
endif()
