name: runtime-linux-x64-gcc

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
          
    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.7

    - name: Install Conan
      run: |
        pip install conan
        
    - name: Configure Conan
      shell: bash
      run: |
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      env:
        CC: gcc-7
        CXX: g++-7
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -G Ninja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILDING_RUNTIME=TRUE -DPython3_ROOT_DIR=${pythonLocation}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Install
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --install . --prefix ../install

    - name: Benchmark
      shell: bash
      working-directory: ${{github.workspace}}
      run: ${{github.workspace}}/install/bin/benchnncase > benchnncase.log
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: nncaseruntime-linux-x64-gcc
        path: ${{github.workspace}}/install
        if-no-files-found: error
      
    - name: Upload Benchmark Result
      uses: actions/upload-artifact@v2.2.2
      with:
        name: nncasebenchmark-linux-x64-gcc
        path: ${{github.workspace}}/benchnncase.log
        if-no-files-found: error
